name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: cargo install cargo-all-features
    - run: cargo install cargo-deny
    - name: Build
      run: cargo build-all-features --verbose
      env:
        RUSTFLAGS: -Dwarnings
    - name: Run tests
      run: cargo test-all-features --verbose
      env:
        RUSTFLAGS: -Dwarnings
    - name: Check formatting
      run: cargo fmt --all -- --check
    - name: Run cargo deny
      run: cargo deny check
